name: performance-test

on:
  workflow_run:
    workflows:
      - build
    branches:
      - master
      - release
      - develop
    types:
      - completed

jobs:
  k6:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: k6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Install dependencies
        run: npm ci
        working-directory: ./performance-test
      - name: Transpile and bundle test script
        run: npm run build
        working-directory: ./performance-test
#      - name: Run local k6 test
#        uses: grafana/k6-action@v0.2.0
#        with:
#          filename: performance-test/dist/get-200-status.test.js
