name: stress-test

on:
  workflow_run:
    workflows:
      - build
    branches:
      - master
      - release
      - develop
    types:
      - completed

jobs:
  k6:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: k6
    runs-on: ubuntu-latest
    env:
      working-directory: ./stress-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Install dependencies
        run: npm i
        working-directory: ${{ env.working-directory }}
      - name: Transpile and bundle test script
        run: npm run build
        working-directory: ${{ env.working-directory }}
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: ${{ env.working-directory }}/dist/get-200-status-test.js
